[build]
  builder = "nixpacks"
  buildCommand = "pnpm run build"

[deploy]
  startCommand = "pnpm run db:migrate && pnpm run start"
  # healthcheckPath = "/health"
  # healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5
